"use client";

import { motion, useReducedMotion } from "motion/react";
import { threePlServices } from "@/data/three-pl";

export default function ThreePlNetwork() {
  const reducedMotion = useReducedMotion();
  return <div className="relative lg:min-h-[390px]"><div className="relative hidden min-h-[390px] lg:block"><svg className="absolute inset-0 h-full w-full" viewBox="0 0 650 390" fill="none" aria-hidden="true" focusable="false"><path d="M325 195 105 65M325 195 548 65M325 195 80 325M325 195 570 325M325 195 325 38" stroke="rgb(169 185 216 / .35)" strokeWidth="1" /></svg><motion.div className="absolute left-1/2 top-1/2 flex h-32 w-32 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-[#A9B9D8]/50 bg-primary text-lg font-extrabold tracking-[-0.03em] text-white shadow-[0_0_0_16px_rgb(169_185_216_/_0.06)]" initial={false} whileInView={reducedMotion ? undefined : { scale: 1, opacity: 1 }} viewport={{ once: true }} transition={{ duration: 0.5 }}>3PL</motion.div>{threePlServices.map((service, index) => <motion.div key={service} className={`absolute flex h-16 w-16 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-white/25 bg-primary-dark text-center text-[10px] font-semibold leading-tight text-white/80 ${["left-[16%] top-[17%]", "left-[84%] top-[17%]", "left-[12%] top-[83%]", "left-[87%] top-[83%]", "left-1/2 top-[8%]"][index]}`} initial={false} whileInView={reducedMotion ? undefined : { opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ duration: 0.35, delay: 0.15 + index * 0.08 }}>{service}</motion.div>)}</div><div className="relative lg:hidden"><div className="absolute bottom-6 left-6 top-16 w-px bg-white/25" aria-hidden="true" /><motion.div className="relative mx-auto flex h-24 w-24 items-center justify-center rounded-full border border-[#A9B9D8]/50 bg-primary text-lg font-extrabold text-white" initial={false} whileInView={reducedMotion ? undefined : { opacity: 1 }} viewport={{ once: true }}>3PL</motion.div><div className="mt-8 space-y-4 pl-2">{threePlServices.map((service, index) => <motion.div key={service} className="relative flex items-center gap-5" initial={false} whileInView={reducedMotion ? undefined : { opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ duration: 0.35, delay: index * 0.07 }}><span className="relative z-10 flex h-12 w-12 items-center justify-center rounded-full border border-white/30 bg-primary-dark text-[10px] font-bold text-[#A9B9D8]">0{index + 1}</span><span className="text-sm font-semibold text-white/80">{service}</span></motion.div>)}</div></div></div>;
}
