import Container from "@/components/ui/container";
import Reveal from "@/components/ui/reveal";

function UnitsGraphic() {
  return <div className="relative overflow-hidden rounded-[var(--radius-lg)] border border-border bg-surface p-6 sm:p-10" aria-hidden="true"><div className="absolute inset-0 opacity-50 [background-image:linear-gradient(rgb(32_48_80_/_0.08)_1px,transparent_1px),linear-gradient(90deg,rgb(32_48_80_/_0.08)_1px,transparent_1px)] [background-size:36px_36px]" /><div className="relative flex min-h-[270px] flex-col justify-between"><div className="flex items-center justify-between text-[10px] font-bold uppercase tracking-[0.2em] text-secondary"><span>Operación adaptable</span><span>GALAGOM / 02</span></div><svg className="h-32 w-full text-primary" viewBox="0 0 520 130" fill="none"><path d="M40 92h425" stroke="currentColor" strokeOpacity=".18" strokeDasharray="5 8" /><path d="M80 92h280c10 0 18-8 18-18V48c0-5-4-9-9-9h-64l-22-22H96c-9 0-16 7-16 16v59Z" fill="rgb(48 70 111 / .1)" stroke="currentColor" strokeWidth="2" /><path d="M110 44h86M221 44h42M319 44h37M117 92a16 16 0 1 0 0 1M335 92a16 16 0 1 0 0 1" stroke="currentColor" strokeWidth="2" /><path d="M382 70h77" stroke="#585E70" strokeWidth="1.5" strokeDasharray="4 5" /><path d="m450 62 10 8-10 8" stroke="#585E70" strokeWidth="1.5" /></svg><div className="flex items-end justify-between"><span className="text-3xl font-extrabold tracking-[-0.04em] text-primary">Carga</span><span className="text-xs font-bold uppercase tracking-[0.15em] text-secondary">A la medida</span></div></div></div>;
}

export default function UnitsSection() {
  return <section id="unidades" className="bg-white py-20 sm:py-28"><Container><div className="grid items-center gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20"><Reveal><UnitsGraphic /></Reveal><Reveal delay={0.1}><div className="max-w-xl"><p className="mb-5 text-xs font-bold uppercase tracking-[0.2em] text-secondary">Unidades</p><h2 className="text-3xl font-extrabold leading-tight tracking-[-0.04em] text-text sm:text-5xl">Capacidad adaptada a cada operación</h2><p className="mt-6 text-base leading-7 text-text-muted sm:text-lg">Contamos con unidades con capacidad a la medida de tu requerimiento. Nos adaptamos a tus procesos para mantener una comunicación fluida y atención personalizada en cada paso.</p></div></Reveal></div></Container></section>;
}
