import Link from "next/link";
import { siteConfig } from "@/data/site";
import QuoteForm from "@/components/forms/quote-form";
import Container from "@/components/ui/container";
import RouteDecor from "@/components/ui/route-decor";

export default function QuoteCta() {
  return <section id="cotizar" className="relative overflow-hidden bg-primary-dark py-20 text-white sm:py-28"><div className="absolute inset-0 opacity-20 [background-image:linear-gradient(120deg,transparent_48%,rgb(255_255_255_/_0.35)_49%,transparent_50%)] [background-size:48px_48px]" /><Container className="relative"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-start lg:gap-20"><div className="lg:sticky lg:top-28"><p className="mb-5 text-xs font-bold uppercase tracking-[0.2em] text-[#A9B9D8]">Cotización</p><h2 className="max-w-xl text-4xl font-extrabold leading-tight tracking-[-0.04em] sm:text-6xl">¿Necesitas mover mercancía?</h2><p className="mt-6 max-w-md text-base leading-7 text-white/70 sm:text-lg">Cuéntanos qué necesitas transportar, almacenar o distribuir. GALAGOM revisará los detalles de tu operación.</p><RouteDecor className="mt-12" /><p className="mt-12 text-sm text-white/65">También puedes <Link className="font-bold text-white underline decoration-white/30 underline-offset-4 hover:decoration-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white" href={siteConfig.phone.telHref}>llamar al {siteConfig.phone.display}</Link>.</p></div><div className="rounded-[var(--radius-lg)] bg-white p-6 text-text shadow-[var(--shadow-soft)] sm:p-10"><div className="mb-8 border-b border-border pb-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-secondary">Cuéntanos tu necesidad</p><p className="mt-3 text-sm leading-6 text-text-muted">Completa la información esencial de tu solicitud.</p></div><QuoteForm /></div></div></Container></section>;
}
